name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_VERSION: 2022.3.19f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Unity Hub
        run: |
          wget -q -nv https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage -O UnityHub.AppImage
          chmod +x UnityHub.AppImage

      - name: Install Unity Version
        run: |
          ./UnityHub.AppImage --headless install --version $UNITY_VERSION

      - name: Activate Unity license
        run: |
          ./UnityHub.AppImage --headless license --username ${{ secrets.UNITY_USERNAME }} --password ${{ secrets.UNITY_PASSWORD }}

      - name: Build WebGL
        run: |
          ./UnityHub.AppImage --headless build --projectPath . --buildTarget WebGL --buildName WebGLBuild --customBuildPath "Builds/WebGL"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Builds/WebGL
