name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_VERSION: 2022.3.19f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Extract Unity Editor
        run: |
          curl -sSL https://download.unity3d.com/download_unity/${UNITY_VERSION}/UnitySetup-${UNITY_VERSION}.exe --output UnitySetup.exe
          sudo apt-get update
          sudo apt-get install unzip
          unzip -qq UnitySetup.exe -d UnityEditor
          chmod +x UnityEditor/UnitySetup-${UNITY_VERSION} && UnityEditor/UnitySetup-${UNITY_VERSION} --unattended --install-location=$HOME/Unity

      - name: Install Unity License
        run: $HOME/Unity/Editor/Unity --quit --batchmode --createManualActivationFile --manualLicenseFile $HOME/Unity/Unity_v${UNITY_VERSION}.alf

      - name: Activate Unity License
        run: $HOME/Unity/Editor/Unity --quit --batchmode --activateManualLicenseFile $HOME/Unity/Unity_v${UNITY_VERSION}.alf

      - name: Build WebGL
        run: $HOME/Unity/Editor/Unity --quit --batchmode --buildTarget WebGL --projectPath . --customBuildTarget WebGL --customBuildName "WebGLBuild" --customBuildPath "Builds/WebGL"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Builds/WebGL
